# SPDX-FileCopyrightText: Alex Turbov <zaufi@pm.me>
# SPDX-License-Identifier: CC0-1.0

version = 1
SPDX-PackageName = "bare-minimum-repo"
SPDX-PackageSupplier = "Alex Turbov <zaufi@pm.me>"
SPDX-PackageDownloadLocation = "https://github.com/zaufi/bare-minimum-repo"

[[annotations]]
path = ".github/commit-message.template"
precedence = "aggregate"
SPDX-FileCopyrightText = "Alex Turbov <zaufi@pm.me>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ".github/pull_request_template.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "Alex Turbov <zaufi@pm.me>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "**.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "Alex Turbov <zaufi@pm.me>"
SPDX-License-Identifier = "CC0-1.0"
